global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  
  - job_name: 'zksync'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3412']

  - job_name: 'zksync_contract_verifier'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3314']

  - job_name: 'zksync_prover'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3315']

  - job_name: 'zksync_witness_generator'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3116']

  - job_name: 'zksync_witness_vector_generator'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3420']

  - job_name: 'zksync_prover_gateway'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3310']

  - job_name: 'zksync_proof_compressor'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:3321']

  - job_name: 'proxy-blob-retriever'
    scrape_interval: '5s'
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:7070']
